#!/usr/bin/env bash
# gen-image: the DETERMINISTIC core of tron:gen-image. The model supplies the subject and
# judges the result; this script handles the mechanical image pipeline.
#
# WHY a script (and why TWO paths): generating images through codex's AGENT LOOP
# (`codex exec` + the built-in image_gen tool) is unreliable headless — the model narrates
# a tool call but the artifact handle isn't surfaced and often nothing lands in
# $CODEX_HOME/generated_images. This is a known codex issue (openai/codex #28102, #19133,
# #23015), not something a prompt tweak fixes. So:
#
#   PATH A (preferred, deterministic): call codex's bundled image CLI directly —
#     $CODEX_HOME/skills/.system/imagegen/scripts/image_gen.py edit|generate --out <path>.
#     It writes exactly where told, defaults to gpt-image-2, and never depends on the agent
#     loop. Requires OPENAI_API_KEY (sourced from ~/.env if present) + the `openai` package.
#
#   PATH B (fallback): the built-in tool via `codex exec -c features.image_generation=true`,
#     then a STRICT host-side copy of an image generated by THIS run. Used only when no API
#     key is available. May fail to produce an artifact (the known issue) — in which case we
#     fail loudly rather than ship a stale image.
#
# Also fixed vs the old hand-assembled call: auth is preflighted before any work (a revoked
# token shows "logged in" but 401s), the subject is mandatory + the medium pinned from the
# references, and the output is verified to be a real, fresh, non-trivial image.
#
# Usage:
#   gen-image.sh <sources-dir-or-file> [subject] [output.png]
#     <sources> : a folder (samples up to 5 images) OR a single image file
#     [subject] : optional text the new image must depict
#     [output]  : optional absolute output path (default: ./generated-<timestamp>.png)
#
# Exit: 0 ok · 2 bad args/no refs · 3 codex auth failed (exec path) · 4 missing dep · 1 no image.
# Prints the absolute output path on stdout (narration on stderr). The SKILL still does the
# vision-based self-verify (does the image actually depict the subject?) — that's judgment.
set -euo pipefail

log() { echo "gen-image: $*" >&2; }

SOURCES="${1:?usage: gen-image.sh <sources-dir-or-file> [subject] [output.png]}"
SUBJECT="${2:-}"
OUTPUT="${3:-$(pwd)/generated-$(date +%Y%m%d-%H%M%S).png}"
mkdir -p "$(dirname "$OUTPUT")"
OUTDIR="$(cd "$(dirname "$OUTPUT")" && pwd)"
OUTPUT="$OUTDIR/$(basename "$OUTPUT")"

# Pull OPENAI_API_KEY from ~/.env if not already in the environment (the user's convention:
# ~/.env is a plain dotenv of global secrets). Only grab that one key; don't source blindly.
if [ -z "${OPENAI_API_KEY:-}" ] && [ -f "$HOME/.env" ]; then
  _k="$(grep -E '^[[:space:]]*OPENAI_API_KEY=' "$HOME/.env" 2>/dev/null | tail -1 | sed -E 's/^[[:space:]]*OPENAI_API_KEY=//; s/^["'\'']//; s/["'\'']$//')"
  [ -n "${_k:-}" ] && export OPENAI_API_KEY="$_k"
fi

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
IMAGE_GEN="$CODEX_HOME/skills/.system/imagegen/scripts/image_gen.py"
PY="$(command -v python3 || command -v python || true)"

# --- 1. Resolve up to 5 reference images ------------------------------------------------
refs=()
if [ -d "$SOURCES" ]; then
  while IFS= read -r f; do refs+=("$f"); done < <(
    find "$SOURCES" -maxdepth 1 -type f \
      \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) \
      | sort | head -5
  )
else
  [ -f "$SOURCES" ] || { log "error: source '$SOURCES' is not a file or directory"; exit 2; }
  refs+=("$SOURCES")
fi
[ "${#refs[@]}" -gt 0 ] || { log "error: no reference images found in $SOURCES"; exit 2; }
log "using ${#refs[@]} reference image(s)."

# --- 2. Build the prompt: subject mandatory, medium pinned from the references -----------
medium_line="Use the attached image(s) as STYLE/MOOD references ONLY — match their medium (infer it: real photography vs illustration — do NOT switch media), lighting, color treatment, contrast, composition, and texture. Do NOT copy their specific subjects or scenes."
if [ -n "$SUBJECT" ]; then
  subj_line="Create a NEW image whose primary, mandatory subject is: ${SUBJECT}."
else
  subj_line="Create a NEW scene similar in subject matter and feel to the references."
fi
prompt="${subj_line} ${medium_line}"

SIZE="${GENIMG_SIZE:-1024x1024}"
QUALITY="${GENIMG_QUALITY:-high}"

# ========================================================================================
# PATH A — deterministic CLI (preferred). Honors --out; no agent loop.
# ========================================================================================
if [ -n "${OPENAI_API_KEY:-}" ] && [ -f "$IMAGE_GEN" ] && [ -n "$PY" ]; then
  log "generating via image_gen.py CLI (deterministic, model gpt-image-2)…"
  # We always have ≥1 reference (required above), so use `edit` with the refs as inputs.
  # (`generate` is the no-input subcommand; only the `edit` subcommand accepts --image.)
  cli=("$PY" "$IMAGE_GEN" edit)
  for r in "${refs[@]}"; do cli+=(--image "$r"); done
  cli+=(--prompt "$prompt" --size "$SIZE" --quality "$QUALITY" --out "$OUTPUT" --force)
  [ -n "${GENIMG_DRY_RUN:-}" ] && cli+=(--dry-run)

  # Dry-run hook for the offline test: print the argv and stop.
  if [ -n "${GENIMG_PRINT_CMD:-}" ]; then printf '%s\n' "${cli[*]}"; exit 0; fi

  if "${cli[@]}" >&2; then
    [ -n "${GENIMG_DRY_RUN:-}" ] && { log "dry-run only; no image written."; exit 0; }
  else
    rc=$?
    # the openai package is the usual missing piece
    if ! "$PY" -c 'import openai' >/dev/null 2>&1; then
      log "ERROR: the 'openai' Python package is required for the CLI path. Install it:"
      log "       uv pip install openai pillow      # or: $PY -m pip install openai pillow"
      exit 4
    fi
    log "image_gen.py failed (rc=$rc)."
    exit 1
  fi

# ========================================================================================
# PATH B — fallback: built-in tool via codex exec (the known-unreliable path).
# ========================================================================================
else
  if [ -z "${OPENAI_API_KEY:-}" ]; then
    log "no OPENAI_API_KEY — falling back to the codex built-in tool (less reliable headless)."
    log "  tip: add OPENAI_API_KEY to ~/.env for the deterministic CLI path."
  fi

  # Preflight codex auth with a REAL round-trip (login status can lie about a revoked token).
  log "preflight: probing codex auth (round-trip)…"
  if ! printf 'Reply with the single word: OK' \
      | codex exec --skip-git-repo-check -s read-only >/dev/null 2>&1; then
    cat >&2 <<'EOF'
gen-image: BLOCKED on codex auth (token revoked/expired, or not logged in).
  Pick one:
    A) run `! codex login`, then tell me to retry
    B) provide OPENAI_API_KEY (prefer adding it to ~/.env) — also unlocks the deterministic CLI
    C) abort
EOF
    exit 3
  fi
  log "preflight: codex auth OK."

  iflags=(); for r in "${refs[@]}"; do iflags+=(-i "$r"); done
  # built-in image_gen saves under $CODEX_HOME/generated_images; we copy the fresh one out.
  exec_prompt="${prompt} Use the built-in image_gen tool to generate it. Just generate it — you do NOT need to move, copy, or save it to any particular path."
  GENROOT="$CODEX_HOME/generated_images"; mkdir -p "$GENROOT"
  STAMP="$(mktemp "${TMPDIR:-/tmp}/gen-image-stamp.XXXXXX")"

  GENIMG_TIMEOUT="${GENIMG_TIMEOUT:-300}"
  TO=(); command -v timeout >/dev/null 2>&1 && TO=(timeout "$GENIMG_TIMEOUT")
  log "generating (codex exec built-in, timeout ${GENIMG_TIMEOUT}s)…"
  # -c features.image_generation=true ensures exec actually OFFERS the tool to the model.
  printf '%s' "$exec_prompt" | "${TO[@]}" codex exec \
    --skip-git-repo-check \
    -c features.image_generation=true \
    --sandbox workspace-write \
    -C "$OUTDIR" \
    "${iflags[@]}" >&2 || log "codex exec returned non-zero/timed out — checking for output anyway."

  # STRICT: only accept an image created by THIS run. Never fall back to newest-overall
  # (that ships a stale image from a prior session and falsely reports success).
  log "collecting fresh image from ${GENROOT}…"
  gen="$(find "$GENROOT" -type f \( -name 'ig_*.png' -o -name '*.png' -o -name '*.webp' \) -newer "$STAMP" -print0 2>/dev/null \
         | xargs -0 ls -t 2>/dev/null | head -1 || true)"
  rm -f "$STAMP"
  if [ -n "${gen:-}" ]; then
    cp "$gen" "$OUTPUT"; log "copied $gen -> $OUTPUT"
  else
    cat >&2 <<EOF
gen-image: ERROR — the codex built-in image_gen tool produced NO new image this run.
  This is a known headless limitation of codex (openai/codex #28102/#19133/#23015), not a
  prompt problem. Refusing to ship a stale image. To make this reliable:
    • add OPENAI_API_KEY to ~/.env (unlocks the deterministic image_gen.py CLI path), or
    • run the generation interactively where the built-in tool is dependable.
EOF
    exit 1
  fi
fi

# --- 3. Verify a real, non-trivial image landed ----------------------------------------
if [ ! -s "$OUTPUT" ]; then log "error: no output at $OUTPUT"; exit 1; fi
if ! file "$OUTPUT" | grep -qiE 'image|png|jpeg'; then
  log "error: output at $OUTPUT is not a valid image"; exit 1
fi
bytes="$(wc -c < "$OUTPUT" | tr -d ' ')"
[ "$bytes" -ge 1024 ] || { log "error: output suspiciously small (${bytes} B)"; exit 1; }
log "done: $OUTPUT (${bytes} bytes)."
echo "$OUTPUT"
